version: '3'
services:
  db:
    image: mariadb/server
    volumes:
      - /home/jaredgurr/portfolio-extra/mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=super03
    networks: 
      - default
    ports:
      - "3306:3306"
  web:
    image: jaredsdev/nodejsapp
    ports: 
      - "8081:8081"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
