version: '3'
services:
  db:
    image: mariadb/server
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=super03
    networks: 
      - default
    ports:
      - "3306:3306"
  web:
    image: jaredsdev/nodejsapp
    ports: 
      - "80:80"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
    volumes:
      - ./src:/src/app
